
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin , yyscanner )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

static void yyrestart ( FILE *input_file , yyscan_t yyscanner );
static void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
static YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size , yyscan_t yyscanner );
static void yy_delete_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
static void yy_flush_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
static void yypush_buffer_state ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
static void yypop_buffer_state ( yyscan_t yyscanner );

static void yyensure_buffer_stack ( yyscan_t yyscanner );
static void yy_load_buffer_state ( yyscan_t yyscanner );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file , yyscan_t yyscanner );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER , yyscanner)

static YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size , yyscan_t yyscanner );
static YY_BUFFER_STATE yy_scan_string ( const char *yy_str , yyscan_t yyscanner );
static YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len , yyscan_t yyscanner );

static void *yyalloc ( yy_size_t , yyscan_t yyscanner );
static void *yyrealloc ( void *, yy_size_t , yyscan_t yyscanner );
static void yyfree ( void * , yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state ( yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  , yyscan_t yyscanner);
static int yy_get_next_buffer ( yyscan_t yyscanner );
static void yynoreturn yy_fatal_error ( const char* msg , yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;
#define YY_NUM_RULES 22
#define YY_END_OF_BUFFER 23
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_acclist[66] =
    {   0,
       10,   23,   20,   22,   20,   22,   19,   22,   20,   22,
       20,   22,   20,   22,   20,   22,   20,   22,   20,   22,
       20,   22,   10,   20,   22,    9,   19,   22,    9,   20,
       22,   20,   22,   20,   22,   20,   22,   20,   22,   20,
       22,   21,    2,   10,    9,   21,    3,    2,    1,    4,
        5,    3,    1,   18,    8,   16,   15,    7,   17,   14,
       11,   17,    6,   13,   12
    } ;

static const flex_int16_t yy_accept[164] =
    {   0,
        1,    1,    2,    3,    5,    7,    9,   11,   13,   15,
       17,   19,   21,   23,   26,   29,   32,   34,   36,   38,
       40,   42,   42,   42,   42,   42,   42,   42,   42,   43,
       43,   44,   44,   44,   44,   44,   44,   45,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   47,   48,   48,   48,   49,   50,   50,   50,   50,
       50,   50,   51,   51,   52,   52,   52,   52,   52,   53,
       53,   53,   54,   54,   55,   55,   55,   55,   55,   55,
       56,   56,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,

       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   59,   59,   59,   60,   60,
       60,   60,   60,   60,   60,   61,   61,   61,   61,   61,
       62,   62,   62,   63,   63,   63,   64,   64,   65,   65,
       65,   66,   66
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    1,    9,   10,
       11,   12,    1,    1,    1,   13,   14,   15,   15,   15,
       15,   16,   15,   15,   15,   17,   17,   18,    1,   19,
        1,    1,   20,    1,   17,   17,   21,   22,   17,   17,
        1,    1,    1,    1,    1,    1,    1,    1,   23,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       24,   25,   26,    1,    1,    1,   27,   28,   17,   17,

       29,   30,   31,   32,   33,   34,    1,   35,   36,   37,
       38,   39,    1,   20,   40,   41,   42,   43,    1,   44,
       45,    1,   46,    1,   47,   48,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[49] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    3,    1,
        4,    1,    1,    1,    5,    5,    6,    1,    1,    7,
        6,    6,    1,    8,    7,    1,    5,    5,    6,    5,
        1,    1,    1,    1,    1,    1,    7,    1,    1,    1,
        7,    1,    7,    7,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[175] =
    {   0,
        0,   39,  392,  393,    5,   19,   24,  367,    4,  376,
      377,  362,    5,   86,   46,   62,  382,    9,  367,  362,
      336,   69,   93,  377,  368,  369,  354,   10,  373,   62,
      376,  365,  350,    5,  332,  333,    0,  106,   12,  325,
      113,  358,   82,   99,  352,  349,  321,  362,  341,  356,
      393,  363,  107,    0,  362,  361,  122,  333,  359,  332,
      126,  133,  136,  139,  350,  142,  123,    0,  356,  141,
      161,  355,  147,  330,  325,   67,  321,  331,  157,  161,
       34,  393,  319,  314,  305,  336,   14,    0,  315,  305,
      309,  322,  316,  301,  301,  161,  310,  299,  325,  317,

      150,  298,  304,   49,   54,  142,  137,   67,  169,  296,
      306,  324,  167,  393,  297,  293,   61,  162,  171,  159,
      167,  194,  199,  275,  266,  207,  248,  242,  201,  211,
        0,  236,  214,  219,  222,  192,  191,  219,  197,  225,
      187,  213,  172,  183,  393,  226,    0,  234,  182,  393,
       93,  107,  393,  209,  237,  240,   70,  393,   15,   10,
      393,  393,  244,  252,  260,  267,  273,  276,  282,  290,
      298,  306,  314,  322
    } ;

static const flex_int16_t yy_def[175] =
    {   0,
      163,  163,  162,  162,  162,  162,  162,  162,  164,  162,
      162,  165,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  166,  164,  162,  167,
      162,  162,  165,  165,  162,  162,   14,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  166,  162,
      162,  162,  164,  168,  162,  162,  165,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  169,  162,  164,
      164,  162,  165,  165,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  169,  164,   71,  162,  162,
      162,  162,  162,  162,  162,  169,  162,  162,  162,  162,

      162,  162,  162,  169,  169,  169,  169,  169,  162,  162,
      162,  162,  162,  162,  162,  162,  169,  169,  169,  169,
      169,  162,  162,  162,  162,  162,  162,  162,  169,  162,
      170,  162,  162,  162,  162,  162,  162,  162,  170,  162,
      162,  171,  162,  172,  162,  162,  173,  162,  171,  162,
      162,  172,  162,  173,  162,  162,  162,  162,  174,  174,
      162,    0,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162
    } ;

static const flex_int16_t yy_nxt[442] =
    {   0,
      162,    5,    6,    7,    8,    9,   22,   23,   23,   29,
       24,   10,  161,   11,   57,   51,   25,  161,   26,   51,
       23,   23,   23,   12,   24,   23,   23,   23,   30,   24,
       34,   35,   26,   36,   30,   81,   82,   26,   30,   13,
       14,   15,   16,    8,    9,   17,   18,   41,   41,   41,
       10,   24,   11,   39,   43,   44,   19,   43,   44,   26,
       20,   96,   12,   41,   41,   41,   96,   24,   76,   39,
       22,   23,   23,   96,   24,   26,   53,   53,   13,   96,
       25,  117,   26,   61,   62,   61,   21,   37,   38,   38,
      129,   24,  118,   39,   23,   23,   23,   25,   24,   26,

       63,   64,   63,  121,   90,   54,   26,   41,   41,   41,
      159,   24,   51,   39,   41,   41,   41,  153,   24,   26,
       39,   70,   70,   73,   81,   82,   26,   61,   62,   61,
      157,   30,   74,   40,   61,   62,   61,   63,   64,   63,
       63,   64,   63,   79,   80,   79,   51,   34,   73,   96,
       83,  113,  114,   84,   96,   87,   87,   74,   79,   80,
       79,   85,   79,   80,   79,   30,   51,  120,  113,  114,
      122,   96,   34,   96,   96,   88,   88,   88,  123,   96,
      119,   88,   88,   96,  150,   30,  129,   88,   88,   88,
       88,  104,  129,  153,  105,  122,  106,  129,  107,  108,

      130,  129,  145,  123,  131,  145,  151,  131,  134,  135,
      134,  138,  130,   96,  158,  150,  131,  158,  148,  131,
      134,  135,  134,  134,  135,  134,  146,  146,  144,  143,
      147,  147,  142,  147,  147,  155,  156,  155,  155,  156,
      155,  155,  156,  155,    4,    4,    4,    4,    4,    4,
        4,    4,   28,  141,   28,   28,   28,   28,   28,   28,
       33,   33,   33,   33,   33,   33,   33,   49,   49,   49,
       49,   49,   49,   49,   49,   28,  140,   28,  137,   28,
       71,   71,   86,   86,   86,  136,   86,   86,   86,   86,
      139,  139,  133,  139,  139,  139,  139,  139,  149,  149,

      149,  149,  149,  149,  149,  149,  152,  152,  152,  152,
      152,  152,  152,  152,  154,  154,  132,  154,  154,  154,
      154,  154,  160,  160,  160,  160,  160,  160,  160,  160,
      128,  127,  126,  125,  124,  116,  115,  112,  111,  110,
      109,  103,  102,  101,  100,   99,   98,   97,   96,   95,
       94,   93,   92,   91,   89,   34,   72,   69,   78,   77,
       76,   75,   72,   55,   69,   68,   50,   52,   67,   66,
       65,   60,   47,   59,   58,   34,   56,   55,   52,   50,
       32,   31,   48,   47,   46,   45,   42,   34,   32,   31,
       27,  162,    3,  162,  162,  162,  162,  162,  162,  162,

      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162
    } ;

static const flex_int16_t yy_chk[442] =
    {   0,
        0,    1,    1,    1,    1,    1,    5,    5,    5,    9,
        5,    1,  160,    1,   34,   28,    5,  159,    5,   87,
        6,    6,    6,    1,    6,    7,    7,    7,    9,    7,
       34,   13,    6,   13,   28,   81,   81,    7,   87,    1,
        2,    2,    2,    2,    2,    2,    2,   15,   15,   15,
        2,   15,    2,   15,   18,   18,    2,   39,   39,   15,
        2,  104,    2,   16,   16,   16,  105,   16,   76,   16,
       22,   22,   22,  117,   22,   16,   30,   30,    2,  108,
       22,  104,   22,   43,   43,   43,    2,   14,   14,   14,
      117,   14,  105,   14,   23,   23,   23,   14,   23,   14,

       44,   44,   44,  108,   76,   30,   23,   38,   38,   38,
      157,   38,   53,   38,   41,   41,   41,  152,   41,   38,
       41,   53,   53,   57,   67,   67,   41,   61,   61,   61,
      151,   53,   57,   14,   62,   62,   62,   63,   63,   63,
       64,   64,   64,   66,   66,   66,   70,   57,   73,  107,
       67,  101,  101,   67,  106,   70,   70,   73,   79,   79,
       79,   67,   80,   80,   80,   70,   71,  107,  113,  113,
      109,  120,   73,   96,  118,   71,   71,   71,  109,  121,
      106,   71,   71,  119,  149,   71,  119,   71,   71,   71,
       71,   96,  118,  144,   96,  122,   96,  121,   96,   96,

      123,  120,  139,  122,  123,  139,  143,  123,  126,  126,
      126,  129,  130,  129,  154,  142,  130,  154,  141,  130,
      134,  134,  134,  135,  135,  135,  140,  146,  138,  137,
      140,  146,  136,  140,  146,  148,  148,  148,  155,  155,
      155,  156,  156,  156,  163,  163,  163,  163,  163,  163,
      163,  163,  164,  133,  164,  164,  164,  164,  164,  164,
      165,  165,  165,  165,  165,  165,  165,  166,  166,  166,
      166,  166,  166,  166,  166,  167,  132,  167,  128,  167,
      168,  168,  169,  169,  169,  127,  169,  169,  169,  169,
      170,  170,  125,  170,  170,  170,  170,  170,  171,  171,

      171,  171,  171,  171,  171,  171,  172,  172,  172,  172,
      172,  172,  172,  172,  173,  173,  124,  173,  173,  173,
      173,  173,  174,  174,  174,  174,  174,  174,  174,  174,
      116,  115,  112,  111,  110,  103,  102,  100,   99,   98,
       97,   95,   94,   93,   92,   91,   90,   89,   86,   85,
       84,   83,   78,   77,   75,   74,   72,   69,   65,   60,
       59,   58,   56,   55,   52,   50,   49,   48,   47,   46,
       45,   42,   40,   36,   35,   33,   32,   31,   29,   27,
       26,   25,   24,   21,   20,   19,   17,   12,   11,   10,
        8,    3,  162,  162,  162,  162,  162,  162,  162,  162,

      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162
    } ;

#define REJECT \
{ \
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yyg->yy_full_match; /* restore poss. backed-over text */ \
++yyg->yy_lp; \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "literate-c.lex"
#define YY_NO_INPUT 1
#line 3 "literate-c.lex"
  #include <stdlib.h>
  #include <stdarg.h>
  #include <sys/wait.h>
  #include <sys/types.h>
  #include <sys/stat.h>
  #include <unistd.h>
  #include <glob.h>
  #include <time.h>
  #include <assert.h>
   
  #undef YY_BUF_SIZE
  #define YY_BUF_SIZE 262144
   
  typedef struct {
    char * error, * warning;
  } Error;
  
  static char C[]      = "\n~~~literatec";
  static char Python[] = "\n~~~python";
  static char Octave[] = "\n~~~matlab";
  static char Bash[] = "\n~~~bash";

  struct MyScanner {
    FILE * in, * out;
    char * page, * basename, * gnuplot, * gnuplot_output, * type, * plotype;
    int i, ncodes, incode, first, line, indent;
    FILE * inbibtex;
    Error * error;
    int nerror, nplots;
  };

#define output_c1(scan, c) fputc(c, scan->out)
#define output_c(c) output_c1(yyextra, c)
#define output_s1(scan, s) fputs(s, scan->out)
#define output_s(s) output_s1(yyextra, s)
  
  static void error_start (struct MyScanner * scan) {
    fprintf (scan->out,
	     "<div class=error id=%d>"
	     "<div id=msg_logo>"
	     "<img src=/img/error.png>"
	     "</div>"
	     "<div id=msg_label>", scan->line + 1);
  }

  static void warning_start (struct MyScanner * scan) {
    fprintf (scan->out,
	     "<div class=message id=%d>"
	     "<div id=msg_logo>"
	     "<img src=/img/warning.png>"
	     "</div>"
	     "<div id=msg_label>", scan->line + 1);
  }

  static void error_end (struct MyScanner * scan) {
    output_s1 (scan, "</div></div>");
  }

  static int check_error (struct MyScanner * scan) {
    int found = 0;
    if (scan->line < scan->nerror) {
      Error * e = &scan->error[scan->line];
      if (e->error || e->warning) {
	if (!scan->first && (scan->incode || scan->plotype))
	  output_s1 (scan, "\n~~~\n");
	if (e->error) {
	  error_start (scan);
	  output_s1 (scan, e->error);
	  free (e->error); e->error = NULL;
	}
	else {
	  warning_start (scan);
	  output_s1 (scan, e->warning);
	  free (e->warning); e->warning = NULL;
	}
	error_end (scan);
	found = 1;
	if (!scan->first && scan->incode && scan->type) {
	  output_s1 (scan, scan->type);
	}
	else if (scan->plotype) {
	  output_c1 (scan, '\n');
	  output_s1 (scan, scan->plotype);
	}
      }
    }
    return found;
  }

  static int spacenb (char * s) {
    int ns = 0;
    while (*s != '\0' && strchr (" \t\v\n\f", *s)) {
      switch (*s) {
      case ' ':  ns++; break;
      case '\t': ns += 8; break;
      case '\n': case '\v': case '\f': ns = 0; break;
      }
      s++;
    }
    return ns;
  }

  static char * acat (const char * s, ...)
  {
    int len = strlen (s) + 1;
    char * c = malloc (len);
    strcpy (c, s);

    va_list ap;
    va_start (ap, s);
    char * s1;
    while ((s1 = va_arg (ap, char *))) {
      len += strlen (s1);
      c = realloc (c, len);
      strcat (c, s1);
    }
    va_end (ap);

    return c;
  }

  static void uline1 (const char * s, struct MyScanner * scan)
  {
    while (*s != '\0')
      if (*s++ == '\n') {
	if (!check_error (scan) && scan->incode && !scan->first &&
	    scan->line > 2)
	  fprintf (scan->out, "\v%d\v", scan->line);
	scan->line++;
      }
  }
  #define uline() uline1(yytext, yyextra)
  
  #define YY_INPUT(buf,result,max_size)			      \
  {							      \
    int c = fgetc (yyextra->in);			      \
    if (c == '\r') /* ignore DOS line endings */	      \
      c = fgetc (yyextra->in);				      \
    if (c == EOF) result = YY_NULL;			      \
    else { buf[0] = c; result = 1; }			      \
  }
#line 732 "lex.yy.c"
#line 733 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#define YY_EXTRA_TYPE struct MyScanner *

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    yy_state_type *yy_state_buf;
    yy_state_type *yy_state_ptr;
    char *yy_full_match;
    int yy_lp;

    /* These are only needed for trailing context rules,
     * but there's no conditional variable for that yet. */
    int yy_looking_for_trail_begin;
    int yy_full_lp;
    int *yy_full_state;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    }; /* end struct yyguts_t */

static int yy_init_globals ( yyscan_t yyscanner );

static int yylex_init (yyscan_t* scanner);

static int yylex_init_extra ( YY_EXTRA_TYPE user_defined, yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

static int yylex_destroy ( yyscan_t yyscanner );

static int yyget_debug ( yyscan_t yyscanner );

static void yyset_debug ( int debug_flag , yyscan_t yyscanner );

static YY_EXTRA_TYPE yyget_extra ( yyscan_t yyscanner );

static void yyset_extra ( YY_EXTRA_TYPE user_defined , yyscan_t yyscanner );

static FILE *yyget_in ( yyscan_t yyscanner );

static void yyset_in  ( FILE * _in_str , yyscan_t yyscanner );

static FILE *yyget_out ( yyscan_t yyscanner );

static void yyset_out  ( FILE * _out_str , yyscan_t yyscanner );

static int yyget_leng ( yyscan_t yyscanner );

static char *yyget_text ( yyscan_t yyscanner );

static int yyget_lineno ( yyscan_t yyscanner );

static void yyset_lineno ( int _line_number , yyscan_t yyscanner );

static int yyget_column  ( yyscan_t yyscanner );

static void yyset_column ( int _column_no , yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( yyscan_t yyscanner );
#else
extern int yywrap ( yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  , yyscan_t yyscanner);
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int , yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * , yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( yyscan_t yyscanner );
#else
static int input ( yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

static int yylex (yyscan_t yyscanner);

#define YY_DECL int yylex (yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! yyg->yy_state_buf )
            yyg->yy_state_buf = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  , yyscanner);
            if ( ! yyg->yy_state_buf )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
		}

		yy_load_buffer_state( yyscanner );
		}

	{
#line 152 "literate-c.lex"


#line 1014 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
		yy_current_state += YY_AT_BOL();

		yyg->yy_state_ptr = yyg->yy_state_buf;
		*yyg->yy_state_ptr++ = yy_current_state;

yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 163 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			*yyg->yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 393 );

yy_find_action:
		yy_current_state = *--yyg->yy_state_ptr;
		yyg->yy_lp = yy_accept[yy_current_state];

find_rule: /* we branch to this label when backing up */

		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yyg->yy_lp && yyg->yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yyg->yy_lp];
					{
					yyg->yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yyg->yy_state_ptr;
			yyg->yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 154 "literate-c.lex"
{
  // start of C documentation comment i.e. "/**"
  uline();
  if (yyextra->ncodes > 0 && !yyextra->first)
    output_s ("\n~~~\n");
  output_c ('\n');
  yyextra->incode = 0;
  yyextra->indent = spacenb (yytext);
  yyextra->type = C;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 165 "literate-c.lex"
{
  uline();
  // end of any C comment block i.e. "*/"
  if (yyextra->incode)
    // end of standard comment
    output_s (yytext);
  else {
    // end of documentation comment
    output_s ("\n");
    yyextra->ncodes++;
    yyextra->incode = 1;
    yyextra->first = 1;
  }
}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 180 "literate-c.lex"
{
  uline();
  if (yyextra->incode) {
    // start of Python documentation comment i.e. """
    if (yyextra->ncodes > 0 && !yyextra->first)
      output_s ("\n~~~\n");
    output_c ('\n');
    yyextra->incode = 0;
    yyextra->indent = spacenb (yytext);
    yyextra->type = Python;
  }
  else {
    // end of Python documentation comment
    output_s ("\n");
    yyextra->ncodes++;
    yyextra->incode = 1;
    yyextra->first = 1;
  }
}
	YY_BREAK
case 4:
/* rule 4 can match eol */
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
yyg->yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 200 "literate-c.lex"
{
  if (yyextra->incode) {
    uline();
    // start of Octave documentation comment i.e. "%{"
    if (yyextra->ncodes > 0 && !yyextra->first)
      output_s ("\n~~~\n");
    output_c ('\n');
    yyextra->incode = 0;
    yyextra->indent = spacenb (yytext);
    yyextra->type = Octave;
  }
  else
    REJECT;
}
	YY_BREAK
case 5:
/* rule 5 can match eol */
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
yyg->yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 215 "literate-c.lex"
{
  if (!yyextra->incode) {
    uline();
    // end of Octave documentation comment i.e. "%}"
    output_s ("\n");
    yyextra->ncodes++;
    yyextra->incode = 1;
    yyextra->first = 1;
  }
  else
    REJECT;
}
	YY_BREAK
case 6:
/* rule 6 can match eol */
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
yyg->yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 228 "literate-c.lex"
{
  if (yyextra->line > 2)
    REJECT;
  uline();
}
	YY_BREAK
case 7:
/* rule 7 can match eol */
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
yyg->yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 234 "literate-c.lex"
{
  if (yyextra->incode) {
    uline();
    // start of Bash documentation comment i.e. ":<<'DOC'"
    if (yyextra->ncodes > 0 && !yyextra->first)
      output_s ("\n~~~\n");
    output_c ('\n');
    yyextra->incode = 0;
    yyextra->indent = spacenb (yytext);
    yyextra->type = Bash;
  }
  else
    REJECT;
}
	YY_BREAK
case 8:
/* rule 8 can match eol */
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
yyg->yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 249 "literate-c.lex"
{
  if (!yyextra->incode) {
    uline();
    // end of Bash documentation comment i.e. "DOC"
    yyextra->ncodes++;
    yyextra->incode = 1;
    yyextra->first = 1;
    output_s ("\n");
  }
  else
    REJECT;
}
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 262 "literate-c.lex"
{
  // empty line
  uline();
  if (!yyextra->incode || !yyextra->first)
    output_s (yytext);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 269 "literate-c.lex"
{
  uline();
  // spaces at the beginning of a line
  if (yyextra->incode) {
    if (yyextra->first && yyextra->type) {
      output_s (yyextra->type);
      output_c ('\n');      
      yyextra->first = 0;
    }
    output_s (yytext);
  }
  else {
    int ns = spacenb (yytext) - yyextra->indent;
    while (ns-- > 0)
      output_c (' ');
  }
}
	YY_BREAK
case 11:
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
yyg->yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 287 "literate-c.lex"
{
  if (yyextra->incode)
    REJECT;
  uline();
  yyextra->gnuplot = strdup (strstr (yytext, "gnuplot") + 7);
  printf ("<div id=\"plot%d\">\n", yyextra->nplots);
  yyextra->plotype = strdup ("~~~ {.bash}");
  fputs (yyextra->plotype, stdout);
}
	YY_BREAK
case 12:
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
yyg->yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 297 "literate-c.lex"
{
  if (yyextra->incode)
    REJECT;
  uline();
  yyextra->gnuplot = strdup (strstr (yytext, "pythonplot") + 10);
  printf ("<div id=\"plot%d\">", yyextra->nplots);
  yyextra->plotype = strdup ("~~~ {.python}");
  fputs (yyextra->plotype, stdout);
}
	YY_BREAK
case 13:
/* rule 13 can match eol */
#line 308 "literate-c.lex"
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 308 "literate-c.lex"
{
  if (yyextra->gnuplot) {
    uline();
    char * s = strchr (yytext, '\'');
    if (!s)
      s = strchr (yytext, '"');
    s++;
    yyextra->gnuplot_output = strdup (s);
    yyextra->gnuplot_output[strlen(s) - 1] = '\0';
    output_s (yytext);
  }
  else
    REJECT;
}
	YY_BREAK
case 15:
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
yyg->yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 323 "literate-c.lex"
{
  if (yyextra->inbibtex || yyextra->incode)
    REJECT;
  uline();
  // bibtex file
  char * command = acat ("awk -f $BASILISK/darcsit/hal2bib.awk | "
			 "bibtex2html -a -d -r "
			 "-no-keywords -noabstract -use-keys "
			 "-nodoc -noheader -q | ",
			 "sed -e 's|</table>.*|</table>|' -e '/<\\/table>/q' > ",
			 yyextra->page, ".bib2html",
			 NULL);
  yyextra->inbibtex = popen (command, "w");
  if (yyextra->inbibtex == NULL) {
    perror (command);
    free (command);
    REJECT;
  }
  free (command);
  yyextra->out = yyextra->inbibtex;
}
	YY_BREAK
case 16:
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
yyg->yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 345 "literate-c.lex"
{
  uline();
  if (!yyextra->incode && yyextra->gnuplot) {
    if (!yyextra->gnuplot_output) {
      char name[30];
      sprintf (name, "_plot%d.svg", yyextra->nplots);
      yyextra->gnuplot_output = strdup (name);
    }
    output_s ("~~~\n</div>\n");
    output_s ("![");
    char * s = yyextra->gnuplot;
    while (*s != '{' && *s != '\0')
      output_c(*s++);
    printf (" (<a href=\"#\" id=\"buttonplot%d\">script</a>)", yyextra->nplots);
    output_s ("](");
    char timestamp[80];
    sprintf (timestamp, "?%ld", time (NULL));
    char * name = acat (yyextra->basename, "/", yyextra->gnuplot_output, timestamp, NULL);
    output_s (name);
    free (name);
    output_s(")");
    if (*s == '{') {
      while (*s != '}' && *s != '\0')
	output_c(*s++);
      output_c ('}');
    }
    printf ("\n\n<div class=\"plot-script\" id=\"afterplot%d\"></div>", yyextra->nplots);
    free (yyextra->gnuplot);
    yyextra->gnuplot = NULL;
    free (yyextra->gnuplot_output);
    yyextra->gnuplot_output = NULL;
    free (yyextra->plotype);
    yyextra->plotype = NULL;
    yyextra->nplots++;
  }
  else if (yyextra->inbibtex) {
    yyextra->out = stdout;
    pclose (yyextra->inbibtex);
    yyextra->inbibtex = NULL;
    char * file = acat (yyextra->page, ".bib2html", NULL);
    FILE * fp = fopen (file, "r");
    if (!fp)
      perror (file);
    else {
      output_s ("<div class=\"bibtex\">\n");
      int c;
      while ((c = fgetc (fp)) != EOF)
	output_c (c);
      fclose (fp);
      output_s ("</div>\n");
    }
    remove (file);
    free (file);
  }
  else
    output_s (yytext);
}
	YY_BREAK
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 403 "literate-c.lex"
{
  if (yyextra->incode)
    REJECT;

  uline();
  char * end = strchr (yytext, ']');
  char * name = strchr (end, '(') + 1;

  char * options = strchr (name, ')');
  *options++ = '\0';

  char * link = strdup (name);

  *end = '\0';
  if (!strcmp(link + strlen(link) - 4, ".mp4") ||
      !strcmp(link + strlen(link) - 4, ".ogv")) {
    char * caption = strchr (yytext, '[') + 1,
      * linked = strstr (options, "link");
    if (linked && strchr ("( \t", linked[-1]) && strchr (") \t", linked[4])) {
      // link to video
      for (int i = 0; i < 4; i++)
	linked[i] = ' ';
      output_s ("<div class=\"figure\">");

      output_s ("<a href=\"");
      output_s (link);
      char tstamp[80];
      snprintf (tstamp, 79, "?%ld", time (NULL));
      fputs (tstamp, yyextra->out);
      output_s ("\">");
      
      output_s ("<img ");
      if (options[0] == '(') {
	*strchr (++options, ')') = '\0';
	output_s (options);
	output_c (' ');
      }
      output_s ("src=\"");
      char * snapshot = strdup (link);
      strcpy (snapshot + strlen(snapshot) - 4, ".jpg");
      char * command = malloc (100 + strlen (link) + strlen (snapshot));
      strcpy (command, "ffmpeg -ss 00:00:10 -i '");
      strcat (command, link);
      strcat (command, "' -frames:v 1 -q:v 2 -loglevel quiet -stats -y '");
      strcat (command, snapshot);
      strcat (command, "'");
      system (command);
      output_s (snapshot);
      output_s ("\">");
      free (snapshot);
      free (command);
      
      output_s ("</a>");
      
      if (caption[0] != '\0') {
	output_s ("<p class=\"caption\">");
	output_s (caption);
	output_s ("</p>");
      }
      output_s ("</div>");
    }
    else { // inline video
      output_s ("<div class=\"figure\"><video ");
      if (options[0] == '(') {
	*strchr (++options, ')') = '\0';
	output_s (options);
	output_c (' ');
      }
      output_s ("controls preload=\"metadata\"><source src=\"");
      output_s (link);
      fprintf (yyextra->out, "?%ld", time (NULL));
      output_s ("\" type = \"video/");
      output_s (!strcmp(link + strlen(link) - 4, ".mp4") ? "mp4" : "ogg");
      output_s ("\"/>Your browser does not support the video tag.</video>");
      if (caption[0] != '\0') {
	output_s ("<p class=\"caption\">");
	output_s (caption);
	output_s ("</p>");
      }
      output_s ("</div>");
    }
  }
  else {
    output_s (yytext);
    output_s ("](");
    output_s (link);
    fprintf (yyextra->out, "?%ld", time (NULL));
    output_c (')');
  }
  free (link);
}
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 495 "literate-c.lex"
{
  // empty link e.g. [Tutorial]()
  uline();
  char * s = strchr (yytext, ']');
  *s = '\0';
  printf ("[%s](%s)", yytext + 1, yytext + 1);
}
	YY_BREAK
case 19:
/* rule 19 can match eol */
YY_RULE_SETUP
#line 503 "literate-c.lex"
{
  uline();
  output_s (yytext);
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 508 "literate-c.lex"
{
  uline();
  if (yyextra->incode && yyextra->first && yyextra->type) {
    output_s (yyextra->type);
    output_c ('\n');
    yyextra->first = 0;
  }
  output_s (yytext);
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 518 "literate-c.lex"
{
  /* STRING_LITERAL */
  uline();
  output_s (yytext);
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 524 "literate-c.lex"
ECHO;
	YY_BREAK
#line 1558 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap( yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  , yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size , yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;
	yy_current_state += YY_AT_BOL();

	yyg->yy_state_ptr = yyg->yy_state_buf;
	*yyg->yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 163 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		*yyg->yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */

	YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 163 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 162);
	if ( ! yy_is_jam )
		*yyg->yy_state_ptr++ = yy_current_state;

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp , yyscan_t yyscanner)
{
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yy_cp = yyg->yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yyg->yy_hold_char;

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = yyg->yy_n_chars + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			yyg->yy_n_chars = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	yyg->yytext_ptr = yy_bp;
	yyg->yy_hold_char = *yy_cp;
	yyg->yy_c_buf_p = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr);
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin , yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
static void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file , yyscanner);
	yy_load_buffer_state( yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
static void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
static YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file , yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
static void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf , yyscanner );

	yyfree( (void *) b , yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer( b , yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
static void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
static void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
static void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER , yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
static YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b , yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
static YY_BUFFER_STATE yy_scan_string (const char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) , yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
static YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n , yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n , yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
static YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
static int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
static int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
static FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
static FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
static int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

static char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
static void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
static void yyset_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
static void yyset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
static void yyset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

static void yyset_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

static int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

static void yyset_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */
static int yylex_init(yyscan_t* ptr_yy_globals)
{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */
static int yylex_init_extra( YY_EXTRA_TYPE yy_user_defined, yyscan_t* ptr_yy_globals )
{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    yyset_extra (yy_user_defined, *ptr_yy_globals);

    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = NULL;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = NULL;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

    yyg->yy_state_buf = 0;
    yyg->yy_state_ptr = 0;
    yyg->yy_full_match = 0;
    yyg->yy_lp = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
static int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER , yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack , yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree( yyg->yy_start_stack , yyscanner );
        yyg->yy_start_stack = NULL;

    yyfree ( yyg->yy_state_buf , yyscanner);
    yyg->yy_state_buf  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

static void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	return malloc(size);
}

static void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

static void yyfree (void * ptr , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 524 "literate-c.lex"


static void revert (char * src, char * bak)
{
  if (src) {
    if (bak) {
      rename (bak, src);
      free (bak);
    }
    else
      remove (src);
    free (src);
  }
}

static char * append (char * s, char * s1)
{
  if (s) {
    if (strstr (s, s1))
      return s;
    char * n = acat (s, "<br>", s1, NULL);
    free (s);
    return n;
  }
  return strdup (s1);
}

static int scan_errors (FILE * fp, char * file, struct MyScanner * scan,
			int output)
{
  char * header;
  header = acat (file, ".c:", NULL);
  char * line = NULL;
  size_t n = 0, nl = 0;
  while (getline (&line, &n, fp) > 0) {
    if (!strncmp (line, header, strlen (header)) ||
	!strncmp (line + 1, header, strlen (header))) {
      char * lineno = line; while (*lineno != ':') lineno++;
      char * type = ++lineno; while (*type != ':' && *type != '\0') type++;
      if (*type == ':') {
	*type++ = '\0';
	if (*type >= '0' && *type <= '9') {
	  while (*type != ':' && *type != '\0') type++;
	  *type++ = '\0';
	}
	while (strchr(" \t", *type)) type++;
	char * msg = type; while (*msg != ':' && *msg != '\0') msg++;
	if (*msg == ':') {
	  *msg++ = '\0';
	  if (msg[strlen(msg)-1] == '\n')
	    msg[strlen(msg)-1] = '\0';
	  if (!strcmp (type, "error") || !strcmp (type, "fatal error") ||
	      !strcmp(type, "warning")) {
	    int line = atoi (lineno);
	    if (line > 0) {
	      if (line > scan->nerror) {
		scan->error = realloc (scan->error, line*sizeof (Error));
		int i;
		for (i = scan->nerror; i < line; i++)
		  scan->error[i].error = scan->error[i].warning = NULL;
		scan->nerror = line;
	      }
	      if (!strcmp (type, "error") || !strcmp (type, "fatal error"))
		scan->error[line-1].error = 
		  append (scan->error[line-1].error, msg);
	      else
		scan->error[line-1].warning = 
		  append (scan->error[line-1].warning, msg);
	    }
	  }
	  free (line); line = NULL;
	}
	else if (type[0] != '\n')
	  line[strlen(line)] = ':';
	else {
	  free (line); line = NULL;
	}	  
      }
    }
    if (output && line) {
      if (nl < 20) {
	char * s = line;
	while (*s != '\0') {
	  if (*s == '`')
	    *s = '\'';
	  s++;
	}
	if (line[strlen(line)-1] == '\n')
	  line[strlen(line)-1] = '\0';
	output_s1 (scan, line);
	output_s1 (scan, "<br>");
      }
      else if (nl == 20)
	output_s1 (scan, "...<br>");
      nl++;
    }
    free (line); line = NULL;
  }
  free (header);

  return scan->nerror;
}

static int root_is (const char * path, const char * root)
{
  return !strncmp (path, root, strlen(root)) &&
    (path[strlen(root)] == '\0' || path[strlen(root)] == '/');
}

static int tail_is (const char * path, const char * tail)
{
  int plen = strlen (path);
  int tlen = strlen (tail);
  return plen >= tlen && !strcmp (&path[plen - tlen], tail);
}

static void usage (struct MyScanner * scan)
{
  char * s = acat (scan->page, ".itags", NULL);
  FILE * fp = fopen (s, "r");
  if (!fp)
    perror (s);
  else {
    char type[10], title[80], file[80], line[10];
    int nf = 0, ne = 0, nt = 0;
    while (fscanf (fp, "%s %[^\t]\t%s %s", type, title, file, line) == 4) {
      nf++;
      if (root_is (file, "/src/test")) nt++;
      if (root_is (file, "/src/examples")) ne++;
    }
    if (nf > 0) {
      output_s1 (scan, "## Usage\n");
      rewind (fp);
      while (fscanf (fp, "%s %[^\t]\t%s %s", type, title, file, line) == 4)
	if (!root_is (file, "/src/test") &&
	    !root_is (file, "/src/examples")) {
	  output_s1 (scan, "* ["); output_s1 (scan, title); 
	  output_s1 (scan, "](");
	  output_s1 (scan, file); output_s1 (scan, ")\n");
	}
      if (ne > 0) {
	output_s1 (scan, "\n### Examples\n");
	rewind (fp);
	while (fscanf (fp, "%s %[^\t]\t%s %s", type, title, file, line) == 4)
	  if (root_is (file, "/src/examples")) {
	    output_s1 (scan, "* ["); output_s1 (scan, title); 
	    output_s1 (scan, "](");
	    output_s1 (scan, file); output_s1 (scan, ")\n");
	  }
      }
      if (nt > 0) {
	output_s1 (scan, "\n### Tests\n");
	rewind (fp);
	while (fscanf (fp, "%s %[^\t]\t%s %s", type, title, file, line) == 4)
	  if (root_is (file, "/src/test")) {
	    output_s1 (scan, "* ["); output_s1 (scan, title); 
	    output_s1 (scan, "](");
	    output_s1 (scan, file); output_s1 (scan, ")\n");
	  }
      }
    }
    fclose (fp);
  }
  free (s);
}

void literate (FILE * fp, const char * page, int code)
{
  yyscan_t scanner;
  struct MyScanner sdata;
  sdata.in = fp;
  sdata.inbibtex = NULL;

  if (code) {
    if (tail_is (page, ".c") || tail_is (page, ".h"))
      sdata.type = C;
    else if (tail_is (page, ".m"))
      sdata.type = Octave;
    else if (tail_is (page, ".py"))
      sdata.type = Python;
    else
      sdata.type = Bash;
    sdata.first = 1;
    sdata.ncodes = 1;
  }
  else {
    sdata.type = NULL;
    sdata.first = 0;
    sdata.ncodes = 0;
  }
  sdata.incode = code;

  sdata.plotype = NULL;
  sdata.indent = 0;
  sdata.out = stdout;
  sdata.i = 0;
  sdata.error = NULL;
  sdata.nerror = sdata.nplots = 0;
  sdata.line = 1;
  sdata.page = strdup (page);
  sdata.basename = strdup (page);  
  char * s = &(sdata.basename[strlen(sdata.basename) - 1]);
  while (*s != '.' && s != sdata.basename) s--;
  if (*s == '.')
    *s = '\0';
  sdata.gnuplot = sdata.gnuplot_output = NULL;

  if (tail_is (page, ".c")) {
    char * page1 = strdup (page);
    char * file = &page1[strlen(page1) - 2];
    *file-- = '\0';
    while (file != page1 && *file != '/')
      file--;
    if (file != page1)
      *file++ = '\0';

    // scan for errors
    {
      char * fail = acat (file, "/fail", NULL);
      FILE * fp = fopen (fail, "r");
      if (fp) {
	scan_errors (fp, file, &sdata, 0);
	fclose (fp);
      }
      free (fail);
    }

    // scan for warnings
    {
      char * warn = acat (file, "/warn", NULL);
      FILE * fp = fopen (warn, "r");
      if (fp) {
	scan_errors (fp, file, &sdata, 0);
	fclose (fp);
      }
      free (warn);
    }
    
    free (page1);
  }

  yylex_init_extra (&sdata, &scanner);
  yyset_out (stdout, scanner);
  yyset_debug (2, scanner);
  yylex (scanner);
  yylex_destroy (scanner);

  if (sdata.ncodes > 0 && sdata.incode && !sdata.first)
    output_s1 ((&sdata), "\n~~~\n");

  if (sdata.ncodes > 0 && tail_is (page, ".h"))
    usage (&sdata);

#if 0
  fputc ('"', stderr);
  fputs (sdata.output, stderr);
  fputs ("\"\n", stderr);
#endif

  int i;
  for (i = 0; i < sdata.nerror; i++) {
    free (sdata.error[i].error);
    free (sdata.error[i].warning);
  }
  free (sdata.error);
  free (sdata.page);
  free (sdata.basename);
}

int main (int argc, char * argv[])
{
  if (argc != 3) {
    fprintf (stderr, "usage: ./literate FILE CODE\n");
    return 1;
  }
  char * name = acat (argv[1], ".page", NULL);
  FILE * f = fopen (name, "r");
  if (!f)
    f = fopen (argv[1], "r");
  if (!f) {
    perror (name);
    return 1;
  }
  free (name);

  literate (f, argv[1], atoi(argv[2]));
  return 0;
}


